# Generated by Django 4.1.5 on 2023-01-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.user"
            ),
        ),
    ]
