# Generated by Django 4.1.5 on 2023-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="image-products/"),
        ),
    ]
