# Generated by Django 4.1.5 on 2023-01-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="icon",
            field=models.ImageField(upload_to="icons/"),
        ),
    ]
