# Generated by Django 4.1.5 on 2023-01-24 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cnpj", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
                ("birth_date", models.DateField()),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("Cosméticos", "Cosméticos"),
                            ("Confecções", "Confecções"),
                            ("Bijuterias", "Bijuterias"),
                            ("Construção e ferramentas", "Construção e ferramentas"),
                            ("Alimentação", "Alimentação"),
                            ("Variedades", "Variedades"),
                            ("Calçados", "Calçados"),
                            ("Decoração", "Decoração"),
                            ("Eletrônicos", "Eletrônicos"),
                        ],
                        default="-------------",
                        max_length=200,
                    ),
                ),
                ("icon", models.ImageField(upload_to="icons/")),
                ("is_client", models.BooleanField(default=False)),
                ("is_store", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
