# Generated by Django 4.1.5 on 2023-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_clients_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="stores",
            name="cnpj",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
