# Generated by Django 4.1.5 on 2023-01-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user"),
        ("company", "0002_alter_products_store"),
        ("client", "0002_alter_requests_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Clients",
        ),
        migrations.DeleteModel(
            name="Stores",
        ),
    ]
