# Generated by Django 4.1.5 on 2023-01-21 17:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_clients_icon"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="clients",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="stores",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="stores",
            name="cnpj",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
