# Generated by Django 4.1.5 on 2023-01-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_clients_managers_alter_stores_managers_and_more"),
        ("main", "0006_alter_user_birth_date_alter_user_contact_and_more"),
    ]

    operations = []
